ALL_USERS_RETRIVE_SUCCESSFULLY='All users retrieved successfully' 
SINGLE_USER_RETRIVE_SUCCESSFULLY='Single user retrieved successfully'
USER_NOT_FOUND='No User Found'
CREATE_USER_SUCCESSFULLY='User created successfully'
UPDATE_USER_SUCCESSFULLY='User updated successfully'
DELETE_USER_SUCCESSFULLY='User deleted successfully'

ALL_PUBLISHERS_RETRIEVED_SUCCESSFULLY = 'All publishers retrieved successfully'
SINGLE_PUBLISHER_RETRIEVED_SUCCESSFULLY = 'Single publisher retrieved successfully'
PUBLISHER_NOT_FOUND = 'No Publisher Found'
CREATE_PUBLISHER_SUCCESSFULLY = 'Publisher created successfully'
UPDATE_PUBLISHER_SUCCESSFULLY = 'Publisher updated successfully'
DELETE_PUBLISHER_SUCCESSFULLY = 'Publisher deleted successfully'

ALL_CUSTOMERS_RETRIEVED_SUCCESSFULLY = 'All customers retrieved successfully'
SINGLE_CUSTOMER_RETRIEVED_SUCCESSFULLY = 'Single customer retrieved successfully'
CUSTOMER_NOT_FOUND = 'No customer Found'
CREATE_CUSTOMER_SUCCESSFULLY = 'Customer created successfully'
UPDATE_CUSTOMER_SUCCESSFULLY = 'Customer updated successfully'
DELETE_CUSTOMER_SUCCESSFULLY = 'Customer deleted successfully'

ALL_CARTS_RETRIEVED_SUCCESSFULLY = 'All carts retrieved successfully'
SINGLE_CART_RETRIEVED_SUCCESSFULLY = 'Single cart retrieved successfully'
CART_NOT_FOUND = 'No Cart Found'
CREATE_CART_SUCCESSFULLY = 'Cart created successfully'
UPDATE_CART_SUCCESSFULLY = 'Cart updated successfully'
DELETE_CART_SUCCESSFULLY = 'Cart deleted successfully'

ALL_BOOKS_RETRIEVED_SUCCESSFULLY = 'All books retrieved successfully'
SINGLE_BOOK_RETRIEVED_SUCCESSFULLY = 'Single book retrieved successfully'
BOOK_NOT_FOUND = 'No Book Found'
CREATE_BOOK_SUCCESSFULLY = 'Book created successfully'
UPDATE_BOOK_SUCCESSFULLY = 'Book updated successfully'
DELETE_BOOK_SUCCESSFULLY = 'Book deleted successfully'

ALL_ORDERS_RETRIEVED_SUCCESSFULLY = 'All orders retrieved successfully'
SINGLE_ORDER_RETRIEVED_SUCCESSFULLY = 'Single order retrieved successfully'
ORDER_NOT_FOUND = 'No Order Found'
CREATE_ORDER_SUCCESSFULLY = 'Order created successfully'
UPDATE_ORDER_SUCCESSFULLY = 'Order updated successfully'
DELETE_ORDER_SUCCESSFULLY = 'Order deleted successfully'

ALL_PAYMENTS_RETRIEVED_SUCCESSFULLY = 'All payments retrieved successfully'
SINGLE_PAYMENT_RETRIEVED_SUCCESSFULLY = 'Single payment retrieved successfully'
PAYMENT_NOT_FOUND = 'No Payment Found'
CREATE_PAYMENT_SUCCESSFULLY = 'Payment done successfully'
DELETE_PAYMENT_SUCCESSFULLY = 'Payment deleted successfully'

ALL_COMPANIES_RETRIEVED_SUCCESSFULLY = 'All companies retrieved successfully'
SINGLE_COMPANY_RETRIEVED_SUCCESSFULLY = 'Single company retrieved successfully'
COMPANY_NOT_FOUND = 'No company Found'
CREATE_COMPANY_SUCCESSFULLY = 'Company create successfully'
UPDATE_COMPANY_SUCCESSFULLY = 'Company updated successfully'
DELETE_COMPANY_SUCCESSFULLY = 'Company deleted successfully'